name: Kikit Log
description: Flutter 프론트엔드 앱개발자 Kikit의 개발 블로그
meta_description: "Flutter Frontend App developer kikit's blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
domain_name: "https://kikit-haha.github.io/"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "kikit"

# Disqus config
disqus-shortname: ""
